### ISSUE TITLE
Adding phynder to bioconda

### ISSUE THREAD

**Issue by jfy133** [richarddurbin/phynder#2]
I was asked if I could investigate putting phynder (or rather [pathPhynder](https://github.com/ruidlpm/pathPhynder), which has phynder as a dependency) onto [bioconda](https://bioconda.github.io/) (a bioinformatics tool package repository for the conda package manager).

I was wondering if you would a) be OK with this, and b) if so if it would be possible to make a GitHub release to have a stable tarball for downloading. That way it would be possible to make a bioconda recipe.

**Comment by richarddurbin** [comment]
Yes, that would all be fine.  I just have to work out how to make a GitHub release.  I will aim to do that now.

**Comment by jfy133** [comment]
Thank you very much!

If it helps: on teh main page of repository, on the right hand bar you should have a 'releases' section, 

If you click on that you can press 'draft a new release', then add a version tag a the top, a title and a short description in the boxes. It would be important to make sure that 'set as the latest release' _is_ checked for bioconda, and then finally publish release. 

A tarball should be made automatically for you.

**Comment by richarddurbin** [comment]
I think I just did this.  But I didn't press "draft".  Actually I now see that there is an issue #1 about a redefinition of typedef.  Is that a problem for you?  Should I fix it and reissue a revised release?

**Comment by jfy133** [comment]
> I think I just did this. But I didn't press "draft". 

Also fine, I see the reelase - thank you very much! I'll take a stab at the bioconda recipe some point today.

> Actually I now see that there is an issue #1 about a redefinition of typedef. Is that a problem for you? Should I fix it and reissue a revised release?

For me personally no. But I guess bug fixes and the new release are always welcome (a nice thing about bioconda is it tries to automatically make new package recipes whenever it detects a new release on a software's repository)!

**Comment by jfy133** [comment]
Hi @richarddurbin Just FYI, `phynder` is now on bioconda :) https://bioconda.github.io/recipes/phynder/README.html?highlight=phynder#package-package%20&#x27;phynder&#x27;

Sorry it too such a long time, a baby 'got in the way' and I had to do a lot of debugging to get it to install on bioconda with minimal experience of `make` and compilation etc.

If you want to add a badge to the README of this repo saying it's availalbe on bioconda, see the info here: https://bioconda.github.io/recipes/phynder/README.html?highlight=phynder#link-to-this-page

Otherwise installation instuctions:

```bash
conda create -n phynder -c bioconda phynder
conda activate phynder
conda deactivate
```

**Comment by richarddurbin** [comment]
Thanks very much James

And congratulations on your baby!

Best wishes

Richard

From: James A. Fellows Yates ***@***.***>
Date: Wednesday, 13 March 2024 at 09:06
To: richarddurbin/phynder ***@***.***>
Cc: Richard Durbin ***@***.***>, Mention ***@***.***>
Subject: Re: [richarddurbin/phynder] Adding phynder to bioconda (Issue #2)

Hi @richarddurbin<https://github.com/richarddurbin> Just FYI, phynder is now on bioconda :) https://bioconda.github.io/recipes/phynder/README.html?highlight=phynder#package-package%20&#x27;phynder&#x27<https://bioconda.github.io/recipes/phynder/README.html?highlight=phynder#package-package%20'phynder&#x27>;

Sorry it too such a long time, a baby got in the way and I had to do a lot of debugging to get it to install on bioconda with minimal experience of make and compilation etc.

If you want to add a badge to the README of this repo saying it's availalbe on bioconda, see the info here: https://bioconda.github.io/recipes/phynder/README.html?highlight=phynder#link-to-this-page

Otherwise installation instuctions:

conda create -n phynder -c bioconda phynder

conda activate phynder

conda deactivate

**Comment by jfy133** [comment]
Thank you!
